// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * A minimal QR encoder, so a phone can be handed a URL by pointing a
 * camera at a screen.
 *
 * Deliberately narrow: byte mode only, error correction level M,
 * versions 1 through 10. That covers every URL this portal needs to
 * put on a screen (a deployment link is about 70 characters, which
 * lands at version 5) and nothing else. Widening it means extending
 * the four tables below, not restructuring anything.
 *
 * Written rather than depended on because the whole feature is one
 * SVG on two pages, and this workspace is where tests actually run.
 * The risk in hand-rolling it is specific and nasty: a subtly wrong
 * Reed-Solomon block, mask or format field still renders a
 * plausible-looking square of dots that some scanners read and
 * others refuse. There is no visual tell. So `qr.spec.ts` pins every
 * matrix, bit for bit, against fixtures generated by a mature
 * library, including all eight masks per case so a placement bug and
 * a mask-selection bug cannot cancel out.
 *
 * Reference: ISO/IEC 18004. Tables transcribed for EC level M only.
 */

/** Total data codewords per version at EC level M. */
const DATA_CODEWORDS_M = [
  16, 28, 44, 64, 86, 108, 124, 154, 182, 216,
] as const;

/** EC codewords per block, per version, at EC level M. */
const EC_PER_BLOCK_M = [10, 16, 26, 18, 24, 16, 18, 22, 22, 26] as const;

/**
 * Block layout per version at EC level M as
 * [group1Blocks, group1DataCodewords, group2Blocks, group2DataCodewords].
 * Group 2 blocks each hold one more codeword than group 1.
 */
const BLOCKS_M: ReadonlyArray<readonly [number, number, number, number]> = [
  [1, 16, 0, 0],
  [1, 28, 0, 0],
  [1, 44, 0, 0],
  [2, 32, 0, 0],
  [2, 43, 0, 0],
  [4, 27, 0, 0],
  [4, 31, 0, 0],
  [2, 38, 2, 39],
  [3, 36, 2, 37],
  [4, 43, 1, 44],
];

/** Alignment pattern centre coordinates per version (empty for v1). */
const ALIGNMENT: ReadonlyArray<readonly number[]> = [
  [],
  [6, 18],
  [6, 22],
  [6, 26],
  [6, 30],
  [6, 34],
  [6, 22, 38],
  [6, 24, 42],
  [6, 26, 46],
  [6, 28, 50],
];

const MAX_VERSION = 10;

// ---------------------------------------------------------------- GF(256)

const GF_EXP = new Uint8Array(512);
const GF_LOG = new Uint8Array(256);
{
  let x = 1;
  for (let i = 0; i < 255; i += 1) {
    GF_EXP[i] = x;
    GF_LOG[x] = i;
    x <<= 1;
    // 0x11D is the QR primitive polynomial.
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i += 1) GF_EXP[i] = GF_EXP[i - 255]!;
}

function gfMul(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return GF_EXP[GF_LOG[a]! + GF_LOG[b]!]!;
}

/**
 * Generator polynomial for `degree` error-correction codewords,
 * returned HIGHEST degree first so index 0 is the monic leading 1.
 *
 * The accumulation below naturally builds lowest-first, which is the
 * easy ordering to write and the wrong one to hand to the shift
 * register in `ecCodewords`. Getting this backwards leaves the data
 * codewords perfectly correct and only the EC block wrong, so the
 * symbol still renders and only fails once a scanner tries to verify
 * it. Hence the reverse, and hence the fixtures.
 */
function generatorPoly(degree: number): Uint8Array {
  let poly = new Uint8Array([1]);
  for (let d = 0; d < degree; d += 1) {
    const next = new Uint8Array(poly.length + 1);
    for (let i = 0; i < poly.length; i += 1) {
      next[i] = (next[i]! ^ gfMul(poly[i]!, GF_EXP[d]!)) & 0xff;
      next[i + 1] = (next[i + 1]! ^ poly[i]!) & 0xff;
    }
    poly = next;
  }
  return poly.reverse();
}

/** Reed-Solomon remainder: the EC codewords for one data block. */
function ecCodewords(data: Uint8Array, count: number): Uint8Array {
  const gen = generatorPoly(count);
  const rem = new Uint8Array(count);
  for (const byte of data) {
    const factor = byte ^ rem[0]!;
    rem.copyWithin(0, 1);
    rem[count - 1] = 0;
    if (factor !== 0) {
      for (let i = 0; i < count; i += 1) {
        rem[i] = (rem[i]! ^ gfMul(gen[i + 1]!, factor)) & 0xff;
      }
    }
  }
  return rem;
}

// ------------------------------------------------------------- bit buffer

class BitBuffer {
  private readonly bits: number[] = [];

  put(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i -= 1) {
      this.bits.push((value >>> i) & 1);
    }
  }

  get length(): number {
    return this.bits.length;
  }

  /** Pad to a byte boundary and emit codewords. */
  toBytes(): Uint8Array {
    while (this.bits.length % 8 !== 0) this.bits.push(0);
    const out = new Uint8Array(this.bits.length / 8);
    for (let i = 0; i < out.length; i += 1) {
      let byte = 0;
      for (let b = 0; b < 8; b += 1) byte = (byte << 1) | this.bits[i * 8 + b]!;
      out[i] = byte;
    }
    return out;
  }
}

// ------------------------------------------------------------------ encode

function utf8Bytes(text: string): Uint8Array {
  if (typeof TextEncoder !== 'undefined') return new TextEncoder().encode(text);
  // Node < 11 and odd runtimes. Kept so shared-types stays portable.
  const out: number[] = [];
  for (const ch of text) {
    const cp = ch.codePointAt(0)!;
    if (cp < 0x80) out.push(cp);
    else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
    else if (cp < 0x10000) {
      out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
    } else {
      out.push(
        0xf0 | (cp >> 18),
        0x80 | ((cp >> 12) & 0x3f),
        0x80 | ((cp >> 6) & 0x3f),
        0x80 | (cp & 0x3f),
      );
    }
  }
  return new Uint8Array(out);
}

function pickVersion(byteLength: number): number {
  for (let v = 1; v <= MAX_VERSION; v += 1) {
    // Mode indicator (4 bits) + character count (8 bits for v1-9,
    // 16 for v10+) is the only overhead before the payload.
    const countBits = v >= 10 ? 16 : 8;
    const capacity = DATA_CODEWORDS_M[v - 1]! - Math.ceil((4 + countBits) / 8);
    if (byteLength <= capacity) return v;
  }
  throw new Error(
    `qr: ${byteLength} bytes exceeds version ${MAX_VERSION} at EC level M`,
  );
}

/** Data codewords for the payload: header, terminator, padding. */
function buildCodewords(bytes: Uint8Array, version: number): Uint8Array {
  const total = DATA_CODEWORDS_M[version - 1]!;
  const buf = new BitBuffer();
  buf.put(0b0100, 4); // byte mode
  buf.put(bytes.length, version >= 10 ? 16 : 8);
  for (const b of bytes) buf.put(b, 8);
  // Terminator: up to four zero bits, truncated if the capacity ends.
  const capacityBits = total * 8;
  buf.put(0, Math.min(4, capacityBits - buf.length));
  const codewords = Array.from(buf.toBytes());
  // Alternating pad bytes until the version's data capacity is full.
  // The alternation is indexed from the START of the padding, so the
  // first pad byte is always 0xEC. Keying it off codewords.length
  // instead makes the pair start on 0x11 whenever the payload happens
  // to end on an odd codeword, which corrupts the error-correction
  // block computed over it.
  const PAD = [0xec, 0x11];
  for (let i = 0; codewords.length < total; i += 1) {
    codewords.push(PAD[i % 2]!);
  }
  return new Uint8Array(codewords);
}

/** Interleave data and EC codewords across blocks, per the spec. */
function interleave(data: Uint8Array, version: number): Uint8Array {
  const [g1, g1Len, g2, g2Len] = BLOCKS_M[version - 1]!;
  const ecLen = EC_PER_BLOCK_M[version - 1]!;

  const dataBlocks: Uint8Array[] = [];
  const ecBlocks: Uint8Array[] = [];
  let offset = 0;
  for (let i = 0; i < g1 + g2; i += 1) {
    const len = i < g1 ? g1Len : g2Len;
    const block = data.subarray(offset, offset + len);
    offset += len;
    dataBlocks.push(block);
    ecBlocks.push(ecCodewords(block, ecLen));
  }

  const out: number[] = [];
  const maxData = Math.max(g1Len, g2Len);
  for (let i = 0; i < maxData; i += 1) {
    for (const block of dataBlocks) {
      if (i < block.length) out.push(block[i]!);
    }
  }
  for (let i = 0; i < ecLen; i += 1) {
    for (const block of ecBlocks) out.push(block[i]!);
  }
  return new Uint8Array(out);
}

// ------------------------------------------------------------------ matrix

type Grid = Int8Array[]; // -1 unset, 0 light, 1 dark

function blankGrid(size: number): Grid {
  return Array.from({ length: size }, () => new Int8Array(size).fill(-1));
}

function placeFinder(grid: Grid, size: number, row: number, col: number): void {
  for (let r = -1; r <= 7; r += 1) {
    for (let c = -1; c <= 7; c += 1) {
      const rr = row + r;
      const cc = col + c;
      if (rr < 0 || rr >= size || cc < 0 || cc >= size) continue;
      const inRing =
        (r >= 0 && r <= 6 && (c === 0 || c === 6)) ||
        (c >= 0 && c <= 6 && (r === 0 || r === 6));
      const inCore = r >= 2 && r <= 4 && c >= 2 && c <= 4;
      grid[rr]![cc] = inRing || inCore ? 1 : 0;
    }
  }
}

function placeFunctionPatterns(grid: Grid, size: number, version: number): void {
  placeFinder(grid, size, 0, 0);
  placeFinder(grid, size, 0, size - 7);
  placeFinder(grid, size, size - 7, 0);

  // Timing patterns.
  for (let i = 8; i < size - 8; i += 1) {
    const bit = i % 2 === 0 ? 1 : 0;
    grid[6]![i] = bit;
    grid[i]![6] = bit;
  }

  // Alignment patterns, skipping any that would collide with a finder.
  const centres = ALIGNMENT[version - 1]!;
  for (const r of centres) {
    for (const c of centres) {
      const nearFinder =
        (r <= 8 && c <= 8) ||
        (r <= 8 && c >= size - 9) ||
        (r >= size - 9 && c <= 8);
      if (nearFinder) continue;
      for (let dr = -2; dr <= 2; dr += 1) {
        for (let dc = -2; dc <= 2; dc += 1) {
          const ring = Math.max(Math.abs(dr), Math.abs(dc));
          grid[r + dr]![c + dc] = ring === 1 ? 0 : 1;
        }
      }
    }
  }

  // Dark module: always set, always here.
  grid[size - 8]![8] = 1;

  // Reserve format areas so data placement skips them.
  for (let i = 0; i < 9; i += 1) {
    if (grid[8]![i] === -1) grid[8]![i] = 0;
    if (grid[i]![8] === -1) grid[i]![8] = 0;
  }
  for (let i = 0; i < 8; i += 1) {
    if (grid[8]![size - 1 - i] === -1) grid[8]![size - 1 - i] = 0;
    if (grid[size - 1 - i]![8] === -1) grid[size - 1 - i]![8] = 0;
  }

  // Version information blocks (v7+), 3x6 near the top-right and
  // bottom-left finders.
  if (version >= 7) {
    const bits = versionBits(version);
    for (let i = 0; i < 18; i += 1) {
      const bit = (bits >> i) & 1;
      const r = Math.floor(i / 3);
      const c = size - 11 + (i % 3);
      grid[r]![c] = bit;
      grid[c]![r] = bit;
    }
  }
}

/** BCH(18,6) version information, for versions 7 and up. */
function versionBits(version: number): number {
  let rem = version;
  for (let i = 0; i < 12; i += 1) {
    rem = (rem << 1) ^ ((rem >>> 11) * 0x1f25);
  }
  return ((version << 12) | rem) >>> 0;
}

/** BCH(15,5) format information for EC level M and a mask. */
function formatBits(mask: number): number {
  // 0b00 is EC level M.
  const data = (0b00 << 3) | mask;
  let rem = data;
  for (let i = 0; i < 10; i += 1) {
    rem = (rem << 1) ^ ((rem >>> 9) * 0x537);
  }
  return (((data << 10) | rem) ^ 0x5412) >>> 0;
}

function placeFormat(grid: Grid, size: number, mask: number): void {
  const bits = formatBits(mask);
  for (let i = 0; i < 15; i += 1) {
    // MSB first: bit 14 lands at (8,0) and at (size-1,8). Reading
    // LSB-first here produces a mirrored format field, which is a
    // perfectly plausible-looking code that no scanner accepts.
    const bit = (bits >> (14 - i)) & 1;
    // Copy 1: around the top-left finder.
    if (i < 6) grid[8]![i] = bit;
    else if (i === 6) grid[8]![7] = bit;
    else if (i === 7) grid[8]![8] = bit;
    else if (i === 8) grid[7]![8] = bit;
    else grid[14 - i]![8] = bit;
    // Copy 2: split across the other two finders.
    if (i < 8) grid[size - 1 - i]![8] = bit;
    else grid[8]![size - 15 + i] = bit;
  }
  grid[size - 8]![8] = 1; // dark module, restated after format writes
}

function maskFn(mask: number, r: number, c: number): boolean {
  switch (mask) {
    case 0:
      return (r + c) % 2 === 0;
    case 1:
      return r % 2 === 0;
    case 2:
      return c % 3 === 0;
    case 3:
      return (r + c) % 3 === 0;
    case 4:
      return (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0;
    case 5:
      return ((r * c) % 2) + ((r * c) % 3) === 0;
    case 6:
      return (((r * c) % 2) + ((r * c) % 3)) % 2 === 0;
    default:
      return (((r + c) % 2) + ((r * c) % 3)) % 2 === 0;
  }
}

/** Zigzag data placement, masked as it goes. */
function placeData(
  grid: Grid,
  reserved: boolean[][],
  size: number,
  bytes: Uint8Array,
  mask: number,
): void {
  let bitIndex = 0;
  let upward = true;
  for (let right = size - 1; right >= 1; right -= 2) {
    // Column 6 is the vertical timing pattern and is not part of any
    // pair. REASSIGNING right (rather than substituting a local) is
    // what makes the following decrements land on 5, 3, 1. Using a
    // local here instead walks 6->5, then 4, then 2: column 4 gets
    // encoded twice and column 0 never at all.
    if (right === 6) right = 5;
    for (let step = 0; step < size; step += 1) {
      const r = upward ? size - 1 - step : step;
      for (const c of [right, right - 1]) {
        if (reserved[r]![c]) continue;
        const byte = bytes[bitIndex >> 3];
        // Past the payload the remainder bits are zero.
        const bit = byte === undefined ? 0 : (byte >> (7 - (bitIndex & 7))) & 1;
        bitIndex += 1;
        grid[r]![c] = maskFn(mask, r, c) ? (bit ^ 1) : bit;
      }
    }
    upward = !upward;
  }
}

// ----------------------------------------------------------------- penalty

function penalty(grid: Grid, size: number): number {
  let score = 0;

  // Rule 1: runs of five or more same-coloured modules in a line.
  for (let i = 0; i < size; i += 1) {
    for (const horizontal of [true, false]) {
      let run = 1;
      for (let j = 1; j < size; j += 1) {
        const cur = horizontal ? grid[i]![j] : grid[j]![i];
        const prev = horizontal ? grid[i]![j - 1] : grid[j - 1]![i];
        if (cur === prev) {
          run += 1;
        } else {
          if (run >= 5) score += run - 2;
          run = 1;
        }
      }
      if (run >= 5) score += run - 2;
    }
  }

  // Rule 2: 2x2 blocks of one colour.
  for (let r = 0; r < size - 1; r += 1) {
    for (let c = 0; c < size - 1; c += 1) {
      const v = grid[r]![c];
      if (
        v === grid[r]![c + 1] &&
        v === grid[r + 1]![c] &&
        v === grid[r + 1]![c + 1]
      ) {
        score += 3;
      }
    }
  }

  // Rule 3: the finder-like 1:1:3:1:1 pattern with four light modules
  // on either side.
  const A = [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0];
  const B = [0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1];
  for (let i = 0; i < size; i += 1) {
    for (let j = 0; j + 11 <= size; j += 1) {
      let matchA = true;
      let matchB = true;
      let matchAv = true;
      let matchBv = true;
      for (let k = 0; k < 11; k += 1) {
        const h = grid[i]![j + k];
        const v = grid[j + k]![i];
        if (h !== A[k]) matchA = false;
        if (h !== B[k]) matchB = false;
        if (v !== A[k]) matchAv = false;
        if (v !== B[k]) matchBv = false;
      }
      if (matchA) score += 40;
      if (matchB) score += 40;
      if (matchAv) score += 40;
      if (matchBv) score += 40;
    }
  }

  // Rule 4: deviation from an even split of dark and light.
  let dark = 0;
  for (let r = 0; r < size; r += 1) {
    for (let c = 0; c < size; c += 1) if (grid[r]![c] === 1) dark += 1;
  }
  const percent = (dark * 100) / (size * size);
  score += Math.floor(Math.abs(percent - 50) / 5) * 10;

  return score;
}

// ------------------------------------------------------------------- public

export interface QrResult {
  /** Module count per side, including the quiet zone? No: excluding. */
  size: number;
  /** Row-major, true = dark. */
  modules: boolean[][];
  version: number;
  mask: number;
}

export interface QrOptions {
  /**
   * Force a mask (0-7) instead of choosing the lowest-penalty one.
   * Exists so tests can compare placement independently of mask
   * selection; production callers should leave it unset.
   */
  mask?: number;
}

/** Encode `text` as a QR matrix. Byte mode, EC level M. */
export function encodeQr(text: string, options: QrOptions = {}): QrResult {
  const bytes = utf8Bytes(text);
  const version = pickVersion(bytes.length);
  const size = version * 4 + 17;
  const payload = interleave(buildCodewords(bytes, version), version);

  // Function patterns are identical across masks, so lay them out
  // once and remember which cells data must skip.
  const base = blankGrid(size);
  placeFunctionPatterns(base, size, version);
  const reserved = base.map((row) => Array.from(row, (v) => v !== -1));

  const build = (mask: number): Grid => {
    const grid = base.map((row) => Int8Array.from(row));
    placeData(grid, reserved, size, payload, mask);
    placeFormat(grid, size, mask);
    return grid;
  };

  let chosen = options.mask;
  let grid: Grid;
  if (chosen === undefined) {
    let best = Number.POSITIVE_INFINITY;
    let bestGrid: Grid | null = null;
    for (let m = 0; m < 8; m += 1) {
      const candidate = build(m);
      const score = penalty(candidate, size);
      if (score < best) {
        best = score;
        chosen = m;
        bestGrid = candidate;
      }
    }
    grid = bestGrid!;
  } else {
    grid = build(chosen);
  }

  return {
    size,
    version,
    mask: chosen!,
    modules: grid.map((row) => Array.from(row, (v) => v === 1)),
  };
}

/**
 * Intermediate values, exposed only so a diagnostic can compare the
 * codeword stream against an independent computation. Not part of the
 * supported surface.
 *
 * @internal
 */
export function __qrInternals(text: string): {
  bytes: Uint8Array;
  version: number;
  codewords: Uint8Array;
  payload: Uint8Array;
  penalties: number[];
} {
  const bytes = utf8Bytes(text);
  const version = pickVersion(bytes.length);
  const codewords = buildCodewords(bytes, version);
  const payload = interleave(codewords, version);
  const size = version * 4 + 17;
  const base = blankGrid(size);
  placeFunctionPatterns(base, size, version);
  const reserved = base.map((row) => Array.from(row, (v) => v !== -1));
  const penalties: number[] = [];
  for (let m = 0; m < 8; m += 1) {
    const grid = base.map((row) => Int8Array.from(row));
    placeData(grid, reserved, size, payload, m);
    placeFormat(grid, size, m);
    penalties.push(penalty(grid, size));
  }
  return { bytes, version, codewords, payload, penalties };
}

/**
 * Render `text` as a standalone SVG string.
 *
 * One `<path>` of rectangles rather than one element per module: a
 * version 5 code is 1,369 modules and half of them are dark, and 700
 * sibling nodes is a lot of DOM for a decoration. `quietZone` is 4
 * modules because scanners need it; without it a code butted against
 * a dark background often will not read.
 */
export function qrSvg(
  text: string,
  opts: QrOptions & { quietZone?: number; className?: string } = {},
): string {
  const { modules, size } = encodeQr(text, opts);
  const quiet = opts.quietZone ?? 4;
  const dim = size + quiet * 2;
  let d = '';
  for (let r = 0; r < size; r += 1) {
    for (let c = 0; c < size; c += 1) {
      if (modules[r]![c]) d += `M${c + quiet} ${r + quiet}h1v1h-1z`;
    }
  }
  const cls = opts.className ? ` class="${opts.className}"` : '';
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${dim} ${dim}"` +
    `${cls} shape-rendering="crispEdges" role="img">` +
    `<rect width="${dim}" height="${dim}" fill="#ffffff"/>` +
    `<path d="${d}" fill="#000000"/></svg>`
  );
}
