// SPDX-License-Identifier: AGPL-3.0-or-later
import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  ServiceUnavailableException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { Prisma } from '@prisma/client';
import { isPointCloudData } from '@gratis-gis/shared-types';

import { PrismaService } from '../prisma/prisma.service.js';
import { ItemsService } from '../items/items.service.js';
import type { AuthUser } from '../auth/auth-sync.service.js';
import { hasCapability } from '../auth/capabilities.js';

/**
 * Server-side analysis jobs (#184, workbench foundation). v1 ships
 * one primitive chain, hillshade-from-point-cloud, executed by the
 * pointcloud-worker service against the analysis_job queue.
 *
 * Tier gating: the server-heavy tier is enabled by the operator
 * through the ANALYSIS_TIERS env (compose sets it where the
 * worker service is deployed; the install doctor reports whether
 * the hardware honestly supports it). Without the tier the
 * endpoints refuse with a plain-language 503 rather than queueing
 * jobs nothing will ever run.
 */
export interface HillshadeParams {
  mode: 'dtm' | 'dsm';
  resolution: number;
  azimuth?: number;
  altitude?: number;
}

/** Raster-size guard for the demo-class box; the worker re-checks. */
const MAX_RASTER_CELLS = 12000 * 12000;

@Injectable()
export class AnalysisService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly items: ItemsService,
    private readonly cfg: ConfigService,
  ) {}

  private assertServerTier(): void {
    const tiers = (this.cfg.get<string>('ANALYSIS_TIERS') ?? '')
      .split(',')
      .map((t) => t.trim())
      .filter(Boolean);
    if (!tiers.includes('server-heavy')) {
      throw new ServiceUnavailableException(
        'Server-side analysis is not enabled on this portal. The administrator can enable it by deploying the analysis worker (see infra docs).',
      );
    }
  }

  async createHillshadeJob(
    user: AuthUser,
    sourceItemId: string,
    params: HillshadeParams,
  ) {
    this.assertServerTier();
    if (!hasCapability(user, 'can_publish_items')) {
      throw new ForbiddenException(
        'Deriving layers requires the contributor or admin role.',
      );
    }
    const source = await this.items.get(user, sourceItemId);
    if (source.type !== 'point_cloud') {
      throw new BadRequestException('Hillshade runs on point cloud items.');
    }
    const data: unknown = source.data;
    if (!isPointCloudData(data) || !data.storageKey) {
      throw new BadRequestException(
        'This point cloud has no uploaded file yet.',
      );
    }

    if (params.mode !== 'dtm' && params.mode !== 'dsm') {
      throw new BadRequestException('mode must be dtm or dsm');
    }
    const resolution = Number(params.resolution);
    if (!Number.isFinite(resolution) || resolution < 0.25 || resolution > 50) {
      throw new BadRequestException(
        'resolution must be between 0.25 and 50 meters',
      );
    }
    const azimuth = clampNumber(params.azimuth, 0, 360, 315);
    const altitude = clampNumber(params.altitude, 1, 90, 45);
    if (data.bounds) {
      const cellsX = (data.bounds[3] - data.bounds[0]) / resolution;
      const cellsY = (data.bounds[4] - data.bounds[1]) / resolution;
      if (cellsX * cellsY > MAX_RASTER_CELLS) {
        throw new BadRequestException(
          'That resolution would produce a raster larger than this server allows. Pick a coarser resolution.',
        );
      }
    }

    // Target item first, so the job row can reference it and the
    // dependency graph sees the provenance edge immediately. It
    // starts as an empty tile_layer; the worker stamps it into the
    // cog-ready state and the pyramid pipeline takes over.
    const modeLabel = params.mode === 'dtm' ? 'terrain' : 'surface';
    const target = await this.items.create(user, {
      type: 'tile_layer',
      title: `${source.title} hillshade (${modeLabel}, ${resolution}m)`,
      description: `Hillshade derived from "${source.title}" (${params.mode.toUpperCase()} at ${resolution}m, sun ${azimuth}deg az / ${altitude}deg alt). Generated by the analysis worker.`,
      tags: ['hillshade', 'derived', 'analysis'],
      data: {
        version: 1,
        format: 'cog',
        kind: 'raster',
        storageKey: '',
        storageUrl: '',
        fileName: '',
        sizeBytes: 0,
        uploadedAt: new Date(0).toISOString(),
      } as Prisma.InputJsonValue,
    });

    const job = await this.prisma.analysisJob.create({
      data: {
        orgId: user.orgId,
        userId: user.id,
        kind: 'hillshade',
        params: { mode: params.mode, resolution, azimuth, altitude },
        sourceItemId,
        targetItemId: target.id,
      },
    });
    return { job, targetItemId: target.id };
  }

  /** Jobs for one source item, newest first; drives the panel. */
  async listJobsForItem(user: AuthUser, sourceItemId: string) {
    // Read ACL on the source item gates the listing.
    await this.items.get(user, sourceItemId);
    return this.prisma.analysisJob.findMany({
      where: { sourceItemId, orgId: user.orgId },
      orderBy: { createdAt: 'desc' },
      take: 20,
    });
  }
}

function clampNumber(
  value: unknown,
  min: number,
  max: number,
  fallback: number,
): number {
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, n));
}
