// SPDX-License-Identifier: AGPL-3.0-or-later
import { randomUUID } from 'node:crypto';

import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  ServiceUnavailableException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { Prisma } from '@prisma/client';
import { isPointCloudData } from '@gratis-gis/shared-types';

import { PrismaService } from '../prisma/prisma.service.js';
import { ItemsService } from '../items/items.service.js';
import type { AuthUser } from '../auth/auth-sync.service.js';
import { hasCapability } from '../auth/capabilities.js';

/**
 * Server-side analysis jobs (#184, workbench foundation). v1 ships
 * one primitive chain, hillshade-from-point-cloud, executed by the
 * pointcloud-worker service against the analysis_job queue.
 *
 * Tier gating: the server-heavy tier is enabled by the operator
 * through the ANALYSIS_TIERS env (compose sets it where the
 * worker service is deployed; the install doctor reports whether
 * the hardware honestly supports it). Without the tier the
 * endpoints refuse with a plain-language 503 rather than queueing
 * jobs nothing will ever run.
 */
export interface HillshadeParams {
  mode: 'dtm' | 'dsm';
  resolution: number;
  azimuth?: number;
  altitude?: number;
}

/** Raster-size guard for the demo-class box; the worker re-checks. */
const MAX_RASTER_CELLS = 12000 * 12000;

@Injectable()
export class AnalysisService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly items: ItemsService,
    private readonly cfg: ConfigService,
  ) {}

  private assertServerTier(): void {
    const tiers = (this.cfg.get<string>('ANALYSIS_TIERS') ?? '')
      .split(',')
      .map((t) => t.trim())
      .filter(Boolean);
    if (!tiers.includes('server-heavy')) {
      throw new ServiceUnavailableException(
        'Server-side analysis is not enabled on this portal. The administrator can enable it by deploying the analysis worker (see infra docs).',
      );
    }
  }

  async createHillshadeJob(
    user: AuthUser,
    sourceItemId: string,
    params: HillshadeParams,
  ) {
    this.assertServerTier();
    if (!hasCapability(user, 'can_publish_items')) {
      throw new ForbiddenException(
        'Deriving layers requires the contributor or admin role.',
      );
    }
    const source = await this.items.get(user, sourceItemId);
    if (source.type !== 'point_cloud') {
      throw new BadRequestException('Hillshade runs on point cloud items.');
    }
    const data: unknown = source.data;
    if (!isPointCloudData(data) || !data.storageKey) {
      throw new BadRequestException(
        'This point cloud has no uploaded file yet.',
      );
    }

    if (params.mode !== 'dtm' && params.mode !== 'dsm') {
      throw new BadRequestException('mode must be dtm or dsm');
    }
    const resolution = Number(params.resolution);
    if (!Number.isFinite(resolution) || resolution < 0.25 || resolution > 50) {
      throw new BadRequestException(
        'resolution must be between 0.25 and 50 meters',
      );
    }
    const azimuth = clampNumber(params.azimuth, 0, 360, 315);
    const altitude = clampNumber(params.altitude, 1, 90, 45);
    if (data.bounds) {
      const cellsX = (data.bounds[3] - data.bounds[0]) / resolution;
      const cellsY = (data.bounds[4] - data.bounds[1]) / resolution;
      if (cellsX * cellsY > MAX_RASTER_CELLS) {
        throw new BadRequestException(
          'That resolution would produce a raster larger than this server allows. Pick a coarser resolution.',
        );
      }
    }

    // Target item first, so the job row can reference it and the
    // dependency graph sees the provenance edge immediately. It
    // starts as an empty tile_layer; the worker stamps it into the
    // cog-ready state and the pyramid pipeline takes over.
    const modeLabel = params.mode === 'dtm' ? 'terrain' : 'surface';
    const target = await this.items.create(user, {
      type: 'tile_layer',
      title: `${source.title} hillshade (${modeLabel}, ${resolution}m)`,
      description: `Hillshade derived from "${source.title}" (${params.mode.toUpperCase()} at ${resolution}m, sun ${azimuth}deg az / ${altitude}deg alt). Generated by the analysis worker.`,
      tags: ['hillshade', 'derived', 'analysis'],
      data: {
        version: 1,
        format: 'cog',
        kind: 'raster',
        storageKey: '',
        storageUrl: '',
        fileName: '',
        sizeBytes: 0,
        uploadedAt: new Date(0).toISOString(),
      } as Prisma.InputJsonValue,
    });

    const job = await this.prisma.analysisJob.create({
      data: {
        orgId: user.orgId,
        userId: user.id,
        kind: 'hillshade',
        params: { mode: params.mode, resolution, azimuth, altitude },
        sourceItemId,
        targetItemId: target.id,
      },
    });
    return { job, targetItemId: target.id };
  }

  /**
   * Bare-earth elevation layer for 3D terrain (#186). Same rails
   * as hillshade; the worker outputs a web-tiled elevation COG and
   * stamps the item 'ready' (no pyramid bake; PNG re-encoding
   * would destroy the float elevation values).
   */
  async createElevationJob(
    user: AuthUser,
    sourceItemId: string,
    params: { resolution: number },
  ) {
    this.assertServerTier();
    if (!hasCapability(user, 'can_publish_items')) {
      throw new ForbiddenException(
        'Deriving layers requires the contributor or admin role.',
      );
    }
    const source = await this.items.get(user, sourceItemId);
    if (source.type !== 'point_cloud') {
      throw new BadRequestException(
        'Elevation layers run on point cloud items.',
      );
    }
    const data: unknown = source.data;
    if (!isPointCloudData(data) || !data.storageKey) {
      throw new BadRequestException(
        'This point cloud has no uploaded file yet.',
      );
    }
    const resolution = Number(params.resolution);
    if (!Number.isFinite(resolution) || resolution < 0.25 || resolution > 50) {
      throw new BadRequestException(
        'resolution must be between 0.25 and 50 meters',
      );
    }
    if (data.bounds) {
      const cellsX = (data.bounds[3] - data.bounds[0]) / resolution;
      const cellsY = (data.bounds[4] - data.bounds[1]) / resolution;
      if (cellsX * cellsY > MAX_RASTER_CELLS) {
        throw new BadRequestException(
          'That resolution would produce a raster larger than this server allows. Pick a coarser resolution.',
        );
      }
    }

    const target = await this.items.create(user, {
      type: 'tile_layer',
      title: `${source.title} elevation (${resolution}m)`,
      description: `Ground elevation surface derived from "${source.title}" at ${resolution}m. Powers 3D terrain in maps.`,
      tags: ['elevation', 'terrain', 'derived', 'analysis'],
      data: {
        version: 1,
        format: 'cog',
        kind: 'raster',
        dem: true,
        storageKey: '',
        storageUrl: '',
        fileName: '',
        sizeBytes: 0,
        uploadedAt: new Date(0).toISOString(),
      } as Prisma.InputJsonValue,
    });

    const job = await this.prisma.analysisJob.create({
      data: {
        orgId: user.orgId,
        userId: user.id,
        kind: 'elevation',
        params: { resolution },
        sourceItemId,
        targetItemId: target.id,
      },
    });
    return { job, targetItemId: target.id };
  }

  /**
   * Visibility (viewshed) from a chosen spot, computed on an
   * elevation layer (the dem-flagged COG the elevation job made).
   * gdal_viewshed in the worker; output is a normal raster overlay
   * layer (transparent where hidden, green where visible) that
   * rides the existing cog-to-pmtiles pyramid rails.
   */
  async createViewshedJob(
    user: AuthUser,
    sourceItemId: string,
    params: {
      lng: number;
      lat: number;
      heightM?: number;
      maxDistanceM?: number;
    },
  ) {
    this.assertServerTier();
    if (!hasCapability(user, 'can_publish_items')) {
      throw new ForbiddenException(
        'Deriving layers requires the contributor or admin role.',
      );
    }
    const source = await this.items.get(user, sourceItemId);
    if (source.type !== 'tile_layer') {
      throw new BadRequestException(
        'Visibility runs on an elevation layer.',
      );
    }
    const data = source.data as {
      dem?: boolean;
      cogStorageKey?: string;
      bbox?: [number, number, number, number];
      maxZoom?: number;
    } | null;
    if (!data?.dem || !data.cogStorageKey) {
      throw new BadRequestException(
        'Visibility needs an elevation layer. Create one from a point cloud first (its page has a "Create elevation layer" button).',
      );
    }
    const lng = Number(params.lng);
    const lat = Number(params.lat);
    if (
      !Number.isFinite(lng) ||
      !Number.isFinite(lat) ||
      Math.abs(lat) > 85 ||
      Math.abs(lng) > 180
    ) {
      throw new BadRequestException('Pick a spot on the map.');
    }
    if (data.bbox) {
      const [w, s, e, n] = data.bbox;
      if (lng < w || lng > e || lat < s || lat > n) {
        throw new BadRequestException(
          "Pick a spot inside the elevation layer's area.",
        );
      }
    }
    const heightM = clampNumber(params.heightM, 0.5, 100, 2);
    const maxDistanceM = clampNumber(params.maxDistanceM, 100, 20000, 1600);
    // Cell guard: the viewshed window is a square of side
    // 2 * distance / resolution pixels. The stored maxZoom implies
    // a floor on the true resolution (worker re-checks exactly).
    const resFloor = 156543.03 / 2 ** (data.maxZoom ?? 19);
    const radiusPx = maxDistanceM / resFloor;
    if ((2 * radiusPx) ** 2 > MAX_RASTER_CELLS) {
      throw new BadRequestException(
        "That distance is too far for this server at this layer's detail. Try a shorter distance.",
      );
    }

    const target = await this.items.create(user, {
      type: 'tile_layer',
      title: `Visible area (${source.title})`,
      description: `What can be seen from ${lat.toFixed(5)}, ${lng.toFixed(5)} at ${heightM}m above the ground, looking up to ${Math.round(maxDistanceM)}m away. Computed on "${source.title}" by the analysis worker. Green means visible from that spot.`,
      tags: ['visibility', 'derived', 'analysis'],
      data: {
        version: 1,
        format: 'cog',
        kind: 'raster',
        storageKey: '',
        storageUrl: '',
        fileName: '',
        sizeBytes: 0,
        uploadedAt: new Date(0).toISOString(),
      } as Prisma.InputJsonValue,
    });

    const job = await this.prisma.analysisJob.create({
      data: {
        orgId: user.orgId,
        userId: user.id,
        kind: 'viewshed',
        params: { lng, lat, heightM, maxDistanceM },
        sourceItemId,
        targetItemId: target.id,
      },
    });
    return { job, targetItemId: target.id };
  }

  /**
   * Contour lines from an elevation layer. The GDAL half runs in
   * the analysis worker (gdal_contour, reprojection, a feet field);
   * the worker then hands the GeoJSON to the API-side analysis
   * bridge, which stages it and rides the EXISTING async import
   * pipeline into the pre-created data_layer below. That keeps
   * every engine write in TypeScript where the engine lives.
   */
  async createContoursJob(
    user: AuthUser,
    sourceItemId: string,
    params: { intervalM?: number },
  ) {
    this.assertServerTier();
    if (!hasCapability(user, 'can_publish_items')) {
      throw new ForbiddenException(
        'Deriving layers requires the contributor or admin role.',
      );
    }
    const source = await this.items.get(user, sourceItemId);
    if (source.type !== 'tile_layer') {
      throw new BadRequestException(
        'Contour lines run on an elevation layer.',
      );
    }
    const data = source.data as {
      dem?: boolean;
      cogStorageKey?: string;
    } | null;
    if (!data?.dem || !data.cogStorageKey) {
      throw new BadRequestException(
        'Contour lines need an elevation layer. Create one from a point cloud first (its page has a "Create elevation layer" button).',
      );
    }
    const intervalM = clampNumber(params.intervalM, 0.5, 500, 3.048);

    const layerId = randomUUID();
    const target = await this.items.create(user, {
      type: 'data_layer',
      title: `Contour lines (${source.title})`,
      description: `Elevation contour lines drawn every ${intervalM.toFixed(2)}m (${(intervalM * 3.28084).toFixed(1)}ft) from "${source.title}". Generated by the analysis worker.`,
      tags: ['contours', 'derived', 'analysis'],
      data: {
        version: 3,
        storageType: 'postgis',
        layers: [
          {
            id: layerId,
            label: 'Contour lines',
            name: 'contours',
            geometryType: 'line',
            fields: [
              {
                name: 'elevation_m',
                type: 'number',
                label: 'Elevation (m)',
                nullable: false,
              },
              {
                name: 'elevation_ft',
                type: 'number',
                label: 'Elevation (ft)',
                nullable: false,
              },
            ],
            editingEnabled: false,
            attachmentsEnabled: false,
          },
        ],
      } as unknown as Prisma.InputJsonValue,
    });

    const job = await this.prisma.analysisJob.create({
      data: {
        orgId: user.orgId,
        userId: user.id,
        kind: 'contours',
        params: { intervalM, layerId },
        sourceItemId,
        targetItemId: target.id,
      },
    });
    return { job, targetItemId: target.id };
  }

  /**
   * Steepness (slope) map from an elevation layer: gdaldem slope
   * colored flat-green to steep-red, on the standard raster rails.
   */
  async createSteepnessJob(user: AuthUser, sourceItemId: string) {
    this.assertServerTier();
    if (!hasCapability(user, 'can_publish_items')) {
      throw new ForbiddenException(
        'Deriving layers requires the contributor or admin role.',
      );
    }
    const source = await this.items.get(user, sourceItemId);
    if (source.type !== 'tile_layer') {
      throw new BadRequestException(
        'Steepness runs on an elevation layer.',
      );
    }
    const data = source.data as {
      dem?: boolean;
      cogStorageKey?: string;
    } | null;
    if (!data?.dem || !data.cogStorageKey) {
      throw new BadRequestException(
        'Steepness needs an elevation layer. Create one from a point cloud first (its page has a "Create elevation layer" button).',
      );
    }

    const target = await this.items.create(user, {
      type: 'tile_layer',
      title: `Steepness map (${source.title})`,
      description: `How steep the ground is, from "${source.title}". Green is flat, yellow is noticeable, red is very steep. Generated by the analysis worker.`,
      tags: ['steepness', 'slope', 'derived', 'analysis'],
      data: {
        version: 1,
        format: 'cog',
        kind: 'raster',
        storageKey: '',
        storageUrl: '',
        fileName: '',
        sizeBytes: 0,
        uploadedAt: new Date(0).toISOString(),
      } as Prisma.InputJsonValue,
    });

    const job = await this.prisma.analysisJob.create({
      data: {
        orgId: user.orgId,
        userId: user.id,
        kind: 'steepness',
        params: {},
        sourceItemId,
        targetItemId: target.id,
      },
    });
    return { job, targetItemId: target.id };
  }

  /** Jobs for one source item, newest first; drives the panel. */
  async listJobsForItem(user: AuthUser, sourceItemId: string) {
    // Read ACL on the source item gates the listing.
    await this.items.get(user, sourceItemId);
    return this.prisma.analysisJob.findMany({
      where: { sourceItemId, orgId: user.orgId },
      orderBy: { createdAt: 'desc' },
      take: 20,
    });
  }
}

function clampNumber(
  value: unknown,
  min: number,
  max: number,
  fallback: number,
): number {
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, n));
}
