// SPDX-License-Identifier: AGPL-3.0-or-later
import { join } from 'node:path';

import {
  ParquetUserError,
  collectParquetFromPath,
  isParquetPath,
  parquetLayerName,
  probeParquetFromPath,
  streamParquetFromPath,
} from './parquet-reader.js';

/**
 * GeoParquet reader tests against a committed 706-byte fixture
 * (three points around Elkins, WV) generated by DuckDB itself, so
 * the geo metadata is exactly what real-world writers produce.
 *
 * These tests use the real @duckdb/node-api binding rather than a
 * mock: the reader's whole job is SQL generation against DuckDB's
 * actual semantics (geo metadata decoding, GEOMETRY typing, value
 * conversion), and a mocked binding would test nothing. The binding
 * ships prebuilds for every platform CI and dev use. The first run
 * in a fresh environment downloads the spatial extension into the
 * per-user extension dir (network is available on dev and CI; prod
 * uses the extension baked into the image), hence the generous
 * timeout.
 */
jest.setTimeout(120_000);

const FIXTURE = join(__dirname, 'fixtures', 'sample.parquet');

interface PointFeature {
  geometry: { type: string; coordinates: [number, number] };
  properties: Record<string, unknown>;
}

describe('isParquetPath', () => {
  it('matches .parquet and .geoparquet case-insensitively', () => {
    expect(isParquetPath('roads.parquet')).toBe(true);
    expect(isParquetPath('ROADS.PARQUET')).toBe(true);
    expect(isParquetPath('parcels.GeoParquet')).toBe(true);
    expect(isParquetPath('C:/tmp/x/sample.parquet')).toBe(true);
  });

  it('rejects other extensions, including lookalikes', () => {
    expect(isParquetPath('roads.gpkg')).toBe(false);
    expect(isParquetPath('parquet.zip')).toBe(false);
    expect(isParquetPath('notaparquet')).toBe(false);
  });
});

describe('parquetLayerName', () => {
  it('uses the file stem, stripping either extension spelling', () => {
    expect(parquetLayerName('/tmp/abc/sample.parquet')).toBe('sample');
    expect(parquetLayerName('C:\\tmp\\Parcels.GeoParquet')).toBe('Parcels');
  });
});

describe('probeParquetFromPath', () => {
  it('reports one layer with schema and count from the fixture', async () => {
    const probe = await probeParquetFromPath(FIXTURE);
    expect(probe.driver).toBe('Parquet');
    expect(probe.layers).toHaveLength(1);
    const layer = probe.layers[0];
    expect(layer).toBeDefined();
    if (!layer) return;
    expect(layer.name).toBe('sample');
    expect(layer.geometryType).toBe('point');
    expect(layer.featureCount).toBe(3);
    // Geometry column must not leak into the field list.
    expect(layer.fields).toEqual([
      { name: 'name', type: 'string' },
      { name: 'value', type: 'number' },
    ]);
  });
});

describe('streamParquetFromPath', () => {
  it('streams all features in batchSize-bounded batches', async () => {
    const batches: Array<{
      rows: Array<{ geometry: unknown; properties: Record<string, unknown> }>;
      progress: { processed: number; total: number };
    }> = [];
    const meta = await streamParquetFromPath(
      FIXTURE,
      undefined,
      async (batch, progress) => {
        batches.push({ rows: batch, progress });
      },
      { batchSize: 2 },
    );

    expect(meta.driver).toBe('Parquet');
    expect(meta.layerName).toBe('sample');
    expect(meta.total).toBe(3);
    // The fixture declares no crs member, which per GeoParquet spec
    // means the OGC:CRS84 default (lon/lat WGS84, no reprojection).
    expect(meta.sourceSrs).toBe('OGC:CRS84');
    expect(meta.fields).toEqual([
      { name: 'name', type: 'string' },
      { name: 'value', type: 'number' },
    ]);

    expect(batches.map((b) => b.rows.length)).toEqual([2, 1]);
    expect(batches.at(-1)?.progress).toEqual({ processed: 3, total: 3 });

    const features = batches
      .flatMap((b) => b.rows)
      .map((r) => r as PointFeature)
      .sort((a, b) => Number(a.properties.value) - Number(b.properties.value));
    expect(features).toHaveLength(3);
    for (const feature of features) {
      expect(feature.geometry.type).toBe('Point');
      const [lng, lat] = feature.geometry.coordinates;
      // All three points sit around Elkins, WV.
      expect(lng).toBeGreaterThan(-79.9);
      expect(lng).toBeLessThan(-79.8);
      expect(lat).toBeGreaterThan(38.9);
      expect(lat).toBeLessThan(39.0);
    }
    expect(features.map((f) => f.properties)).toEqual([
      { name: 'Elkins Depot', value: 1 },
      { name: 'Bell Tower', value: 2 },
      { name: 'Riverbend Park', value: 3 },
    ]);
  });

  it('rejects a sourceLayer that does not match the single layer', async () => {
    await expect(
      streamParquetFromPath(FIXTURE, 'nope', async () => {}),
    ).rejects.toThrow(ParquetUserError);
    await expect(
      streamParquetFromPath(FIXTURE, 'nope', async () => {}),
    ).rejects.toThrow('File has no layer named "nope".');
  });

  it('accepts the stem itself as sourceLayer', async () => {
    const meta = await streamParquetFromPath(FIXTURE, 'sample', async () => {});
    expect(meta.layerName).toBe('sample');
  });
});

describe('collectParquetFromPath', () => {
  it('materializes the same rows as a FeatureCollection', async () => {
    const out = await collectParquetFromPath(FIXTURE, undefined);
    expect(out.driver).toBe('Parquet');
    expect(out.layerName).toBe('sample');
    expect(out.geojson.type).toBe('FeatureCollection');
    expect(out.geojson.features).toHaveLength(3);
    const first = out.geojson.features
      .map((f) => f as PointFeature & { type: string })
      .find((f) => f.properties.value === 1);
    expect(first?.type).toBe('Feature');
    expect(first?.geometry.type).toBe('Point');
    expect(first?.geometry.coordinates[0]).toBeCloseTo(-79.8534, 4);
    expect(first?.geometry.coordinates[1]).toBeCloseTo(38.9256, 4);
  });
});
