-- Hand-written rather than generated by `prisma migrate dev`, to
-- match the surrounding style and because the partial unique index
-- at the bottom has no Prisma schema equivalent.
--
-- Offline basemap packages (#70). An area on a data_collection gets
-- one vector archive cut on the server; every collector downloads
-- that file instead of enumerating tiles for themselves. The area
-- definition lives on the item's data JSON; the builds live here,
-- because they are a work queue that needs claiming, heartbeating
-- and sweeping.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'OfflinePackageStatus'
  ) THEN
    CREATE TYPE "OfflinePackageStatus" AS ENUM (
      'queued', 'building', 'ready', 'failed', 'superseded'
    );
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "offline_package" (
  "id"                UUID                   NOT NULL DEFAULT gen_random_uuid(),
  "org_id"            UUID                   NOT NULL,
  "item_id"           UUID                   NOT NULL,
  "area_id"           TEXT                   NOT NULL,
  "created_by"        UUID                   NOT NULL,
  "status"            "OfflinePackageStatus" NOT NULL DEFAULT 'queued',
  "bbox"              DOUBLE PRECISION[]     NOT NULL,
  "min_zoom"          INTEGER                NOT NULL,
  "max_zoom"          INTEGER                NOT NULL,
  "source_url"        TEXT                   NOT NULL,
  "tile_count"        INTEGER,
  "storage_key"       TEXT,
  "size_bytes"        INTEGER,
  "error_message"     TEXT,
  "created_at"        TIMESTAMP(3)           NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "started_at"        TIMESTAMP(3),
  "finished_at"       TIMESTAMP(3),
  "last_heartbeat_at" TIMESTAMP(3),
  CONSTRAINT "offline_package_pkey" PRIMARY KEY ("id")
);

-- Serves the worker's claim poll.
CREATE INDEX IF NOT EXISTS "offline_package_status_created_idx"
  ON "offline_package" ("status", "created_at");

-- Serves "the current package for this area", which every read of
-- the authoring panel and every field download does.
CREATE INDEX IF NOT EXISTS "offline_package_item_area_status_idx"
  ON "offline_package" ("item_id", "area_id", "status");

-- At most one in-flight build per area.
--
-- Without this, "Build now" queues a second row on a double click,
-- and the automatic-refresh sweep can queue a third while the first
-- is still running, so the same archive gets cut two or three times
-- and the last writer decides which one collectors get. Enforcing it
-- here rather than with a read-then-insert in the service means the
-- API endpoint and the sweep cannot race each other at all.
--
-- Prisma has no syntax for partial indexes, so this is invisible to
-- schema.prisma and `prisma migrate dev` leaves it alone. Same
-- arrangement as the osm_query_cache expires_at index.
CREATE UNIQUE INDEX IF NOT EXISTS "offline_package_one_active_idx"
  ON "offline_package" ("item_id", "area_id")
  WHERE "status" IN ('queued', 'building');
