// SPDX-License-Identifier: AGPL-3.0-or-later
// Builds dist/gratis-field-engine.js: one IIFE, ES2020, no imports, no
// platform globals, exposing `GratisFieldEngine` with `call`,
// `SURFACE`, `SURFACE_NAMES` and `ENGINE_VERSION`. Also writes
// dist/engine-version.json so the Android build can pin the exact
// bytes it ships and refuse to start on a mismatch.
//
// ES2020 rather than the repo's ES2022 because QuickJS tracks the
// spec with a lag and JavaScriptCore on the oldest iOS we would
// support is older still. Class fields and top-level await are the
// features that would bite; esbuild lowers them.

import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createContext, runInContext } from 'node:vm';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, 'dist');
const outFile = join(outDir, 'gratis-field-engine.js');

await mkdir(outDir, { recursive: true });

const result = await build({
  entryPoints: [join(here, 'src', 'index.ts')],
  bundle: true,
  format: 'iife',
  globalName: 'GratisFieldEngine',
  target: ['es2020'],
  platform: 'neutral',
  // No Node or browser resolution conditions: if anything in the
  // import graph reached for a platform module the build should fail
  // here, not on the phone.
  mainFields: [],
  conditions: [],
  outfile: outFile,
  sourcemap: true,
  minify: true,
  legalComments: 'none',
  logLevel: 'info',
  metafile: true,
  banner: {
    js: '// SPDX-License-Identifier: AGPL-3.0-or-later\n// GratisGIS field engine bundle. Generated by packages/field-engine/build.mjs; do not edit.',
  },
});

const js = await readFile(outFile);
const sha256 = createHash('sha256').update(js).digest('hex');

// ENGINE_VERSION is read back out of the built bundle by running it,
// not imported from TypeScript, so the manifest can never describe a
// different engine than the file beside it. The bare vm context is
// also the first place a stray platform global would blow up.
const context = createContext({});
runInContext(js.toString('utf8'), context, { filename: 'gratis-field-engine.js' });
const engineVersion = runInContext('GratisFieldEngine.ENGINE_VERSION', context);
if (!Number.isInteger(engineVersion) || engineVersion < 1) {
  throw new Error(`Built bundle reports a bad ENGINE_VERSION: ${String(engineVersion)}`);
}

await writeFile(
  join(outDir, 'engine-version.json'),
  JSON.stringify(
    {
      engineVersion,
      file: 'gratis-field-engine.js',
      sha256,
      bytes: js.length,
      inputs: Object.keys(result.metafile.inputs).sort(),
    },
    null,
    2,
  ) + '\n',
);
