-- Persist in-portal feedback instead of only emailing it.
--
-- Hand-written rather than generated by `prisma migrate dev`: this dev
-- database has drifted from the migration history, so `migrate dev`
-- asks to reset it (destroying real local test data) and
-- `migrate diff --from-config-datasource` emits the whole drift,
-- including a DROP TABLE on the observation log. The statements below
-- are exactly the feedback-related output of that diff, lifted without
-- the surrounding noise.

-- CreateEnum
CREATE TYPE "FeedbackStatus" AS ENUM ('new', 'handled', 'spam');

-- CreateTable
CREATE TABLE "feedback" (
    "id" UUID NOT NULL,
    "message" TEXT NOT NULL,
    "status" "FeedbackStatus" NOT NULL DEFAULT 'new',
    "name" TEXT,
    "email" TEXT,
    "page_url" TEXT,
    "app_version" TEXT,
    "user_agent" TEXT,
    "viewport" TEXT,
    "user_id" UUID,
    "org_id" UUID,
    "ip_hash" TEXT,
    "screenshot_key" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "handled_at" TIMESTAMP(3),
    "handled_by_id" UUID,

    CONSTRAINT "feedback_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "feedback_status_created_at_idx" ON "feedback"("status", "created_at");

-- CreateIndex
CREATE INDEX "feedback_ip_hash_created_at_idx" ON "feedback"("ip_hash", "created_at");

-- AddForeignKey
-- SET NULL, not CASCADE: losing the reporter must not lose the report.
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_handled_by_id_fkey" FOREIGN KEY ("handled_by_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;
