-- Hand-written rather than generated by `prisma migrate dev`.
--
-- Cancellation for in-flight backups. The signal has to be durable
-- rather than an in-memory AbortController, because prod runs
-- portal-api at 2 replicas behind Caddy: a cancel request lands on
-- whichever replica the proxy picks, which is usually not the one
-- holding the pg_dump. The running backup polls this column.
--
-- Nullable with no default and no backfill: an existing row is simply
-- "never asked to stop", which is exactly right for history.
ALTER TABLE "backup_run" ADD COLUMN "cancel_requested_at" TIMESTAMPTZ;

-- Partial index because the only query is "has anyone asked THIS
-- running backup to stop", polled every couple of seconds for the
-- lifetime of a multi-hour run. Restricting it to live rows keeps it
-- a handful of pages regardless of how much backup history piles up.
CREATE INDEX "backup_run_cancel_requested_idx"
  ON "backup_run" ("id")
  WHERE "status" = 'running';
