-- Superseded: this migration originally created a partial GIN trigram
-- index over the entire (attrs::text) of the observation log to back
-- the map / app attribute search. That broad index turned out to be
-- both redundant and operationally harmful, so it is reduced to a
-- no-op that drops it if a prior run created it.
--
-- Redundant: every searchable v3 field already gets its own per-field
-- trigram index (gin((attrs->>'<field>') gin_trgm_ops), scoped to the
-- layer) created when the field is marked searchable. The search query
-- (DataLayerEngine.searchFeatures) is served fast by those per-field
-- indexes via a bitmap OR; the recheck on attrs::text rides along on
-- the small candidate set. The whole-blob index added nothing the
-- planner needed.
--
-- Harmful: a trigram index over the full attrs JSON of millions of wide
-- rows is multi-GB to build, which overran the prod box's free disk and
-- the statement_timeout and aborted deploys / nightly resets.
--
-- DROP IF EXISTS is idempotent and instant (no table scan, no
-- meaningful lock): safe to (re)apply on every environment, including a
-- fresh install where the index never existed.
DROP INDEX IF EXISTS observation_attrs_trgm;
